# Этап 1: Собираем проект на React
FROM node:alpine as build

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы package.json и package-lock.json (если есть)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы приложения
COPY . .

# Строим проект на React
RUN npm run build

# Этап 2: Сервируем статические файлы с помощью Nginx
FROM nginx:alpine

# Копируем собранные файлы из этапа 'build' в директорию html Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]