version: '3'

services:
  app:
    build:
      context: ./app
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./app:/opt/server
      - ./uploads:/opt/uploads
    env_file:
      - .env
    expose:
      - '4200'
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=123
    expose:
      - '5432'
    networks:
      - app_network

  nginx:
    container_name: proxy_nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
    networks:
      - app_network

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qweasdzxc
    expose:
      - '80'
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge